FROM node:22-alpine

# 작업 디렉토리를 /app으로 설정
WORKDIR /app

# package.json과 package-lock.json 파일을 컨테이너로 복사
COPY package*.json ./

# 의존성 패키지 설치
RUN npm install

# 현재 디렉토리의 모든 파일을 컨테이너로 복사
COPY . .

# 7777 포트 노출
EXPOSE 7777

# 개발 서버 실행 명령
CMD ["npm", "run", "dev"]